server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER  

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Deep5656/microservice-tutorial-config
          clone-on-start: true   


           
