server:
  port: 8081

#Spring MySQL configuration..

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: Deep@1007
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#JPA configuration...

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  

  application:
    name: USER-SERVICE   

  config:
    import: configserver:http://localhost:8085 

  # profiles:
  #   active: prod   

  # eureka client configuration

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-server: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka          


# actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health 
  endpoint:
    health:
      show-details: always        

# resilience4j configuration 
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true 
        eventConsumerBufferSize: 10 
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
           
#retry configuration
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s          
      ratingHotelService1:
        max-attempts: 3
        wait-duration: 5s          



